name: brew test-bot
on:
  push:
    branches: '**'
  pull_request: []
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Ensure homebrew style
        run: |
          set -e
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/ghostlyrics/homebrew-custom"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          brew doctor
          brew readall --aliases ghostlyrics/custom
          brew style ghostlyrics/custom
          brew audit --tap=ghostlyrics/custom
